name: App 2 Workflow

on:
  push:
    paths:
      - 'app2/*'
      - '.github/workflows/app2.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Something in app2 must have changed.."

      - name: List pull requests associated with this commit
        id: list_pull_requests
        run: |
          curl -sB --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --header 'accept: application/vnd.github.groot-preview+json' | jq .
