name: App 2 Workflow

on:
  push:
    paths:
      - 'app2/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Something in app2 must have changed.."